class QuoteController < ApplicationController

	def index
		
	end

	def create
		
		@quote = Quote.new

	end

	def create_save
		require 'securerandom'
		@quote = Quote.create(params[:quote])
		@quote.quote_number = SecureRandom.hex(2).upcase.reverse

		@quote.save

		#Calcualtion has to happen here.
		height = @quote.h_inches / 12 + @quote.h_feet
		width = @quote.w_inches / 12 + @quote.w_feet
		length = @quote.l_inches / 12 + @quote.l_feet
		calc = 2 * ( height * length) + 2 * (height * width)

		if (@quote.ceiling == 1) then
			calc = calc + (length * width)
		end

		if (@quote.insulated == 1) then
			total = calc * 6.5
		else
			total = calc * 8
		end

		
		RestClient.post "https://api:key-857bcl2hvwsj340zb-ov9h2xd4cfj9e3"\
		  "@api.mailgun.net/v2/app2743556.mailgun.org/messages",
		  :from => "OQS <andreasoto@gmail.com>",
		  :to => "andreasoto@gmail.com",
		  :subject => "Quote needs approval",
		  :html => "<h3>Autogenerated Quote</h3> 
		  <ul><li>Total sq ft: ".concat(calc.to_s).concat("</li><li>Total Price: $").concat(total.to_s).concat("</li>
		  	</li>To confirm please go to the following link: http://OQS.heroku.com/quote/confirm_quote?code=").concat(@quote.id.to_s).concat(
		  	"<br/>Client Contact:").concat(@quote.name.to_s).concat(", ").concat(@quote.cell.to_s)


		flash[:notice] = "Quote has been generated and sent to El Sol. An email confirmation will be sent to your email account with a quote number
		if accepted. Use that quote number to create an appointment."
		redirect_to root_url
		# render :text => params
		# logger.debug @quote.inspect
	end

	def confirm_quote
		quote = Quote.find(params[:code])
		height = quote.h_inches / 12 + quote.h_feet
		width = quote.w_inches / 12 + quote.w_feet
		length = quote.l_inches / 12 + quote.l_feet
		calc = 2 * ( height * length) + 2 * (height * width)

		if (quote.ceiling == 1) then
			calc = calc + (length * width)
		end

		if (quote.insulated == 1) then
			total = calc * 6.5
		else
			total = calc * 8
		end

		RestClient.post "https://api:key-857bcl2hvwsj340zb-ov9h2xd4cfj9e3"\
		  "@api.mailgun.net/v2/app2743556.mailgun.org/messages",
		  :from => "OQS <andreasoto@gmail.com>",
		  :to => quote.email,
		  :subject => "Autogenerated quote",
		  :html => "<h3>Drywall Quote</h3> <p>This estimate include the following services:</p>
		  <ul><li>Dry walling</li>
		  <li>Taping</li>
		  <li>Texture</li>
		  <li>Attic insulation</li>
		  <li>Basement insulation</li></ul>
		  Total : $".concat(total.to_s).concat("
		  <p><i>Important Disclaimer: These calculations should be
		  used for estimations only. Please add 10% to your calculation to allow for waste from cutting and potential mistakes.</i></p>
		  <p>If you would like to book an appointment, please visit: http://OQS.heroku.com/ and use the code:<b>
		  ").concat(quote.quote_number).concat("</p></b>")

		  #:text => "Total : $".concat(total.to_s).concat("
		  #	The price includes the drywall, taping, texture and attic insulation.

		  #	If you would like to book an appointment, please visit: http://OQS.heroku.com/ and use the code:
		  #	").concat(quote.quote_number)
		render :text => "<h3>The quote has been sent to the Client.</h3>"
		
	end
end
